### ISSUE TITLE
How do you generate expert trajectories?

### ISSUE THREAD

**Issue by Charlesyyun** [Kaixhin/imitation-learning#11]
I feel confused when looking for expert trajectories, can't find it anywhere.

**Comment by Kaixhin** [comment]
This repo currently uses the datasets provided by [D4RL Pybullet](https://github.com/takuseno/d4rl-pybullet), instead of generating expert trajectories. This ensures that results are more standardised. The dataset loading occurs [here](https://github.com/Kaixhin/imitation-learning/blob/master/environments.py#L86).
